volumes:
  dispatch_db_data:
  dispatch_static:
  dispatch_media:

networks:
  dispatch_network:
    driver: bridge

services:
  # PostgreSQL
  dispatch_db:
    image: postgres:13.10
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - dispatch_db_data:/var/lib/postgresql/data
    networks:
      - dispatch_network
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "md5"
    command: >
      postgres -c listen_addresses='*'

  # Django backend
  dispatch_backend:
    build:
      context: .
    env_file: .env
    volumes:
      - dispatch_static:/app/collected_static
      - dispatch_media:/app/media
      - ./logs:/app/logs        # ğŸ‘ˆ bind mount Ğ´Ğ»Ñ Ğ»Ğ¾Ğ³Ğ¾Ğ²
      - ./data:/app/data        # ğŸ‘ˆ bind mount Ğ´Ğ»Ñ data
      - ./.env:/app/.env:ro   # ğŸ‘ˆ Ğ¼Ğ¾Ğ½Ñ‚Ğ¸Ñ€ÑƒĞµĞ¼ .env Ğ²Ğ½ÑƒÑ‚Ñ€ÑŒ ĞºĞ¾Ğ½Ñ‚ĞµĞ¹Ğ½ĞµÑ€Ğ° (Ğ´Ğ»Ñ cron)
    depends_on:
      - dispatch_db
    networks:
      - dispatch_network
    restart: unless-stopped

  # Nginx
  dispatch_gateway:
    build:
      context: ./gateway/
    ports:
      - "8000:80"
    volumes:
      - dispatch_static:/staticfiles/
      - dispatch_media:/mediafiles/
      - ./logs/nginx:/var/log/nginx   # ğŸ‘ˆ Ğ¾Ñ‚Ğ´ĞµĞ»ÑŒĞ½Ğ°Ñ Ğ¿Ğ°Ğ¿ĞºĞ° Ğ¿Ğ¾Ğ´ nginx-Ğ»Ğ¾Ğ³Ğ¸
    depends_on:
      - dispatch_backend
    networks:
      - dispatch_network
    restart: unless-stopped